# functions

In [2]:
def mprint(matrix):
    for row in matrix:
        print(row)
    print()

In [3]:
def generate_adjacency_matrices(n):
    """
    Generates all adjacency matrices for simple graphs with n vertices.

    Args:
        n: Number of vertices in the graph.

    Returns:
        A list of adjacency matrices.
    """
    def generate_helper(matrix, i, j):
        if i == j:
          generate_helper(matrix, i, j+1)
          return
        if i == n:
          adjacency_matrices.append([row[:] for row in matrix])
          return
        if j == n:
          generate_helper(matrix, i+1, i+1)
          return

        matrix[i][j] = 0
        matrix[j][i] = 0
        generate_helper(matrix, i, j+1)

        matrix[i][j] = 1
        matrix[j][i] = 1
        generate_helper(matrix, i, j+1)
        return

    adjacency_matrices = []
    initial_matrix = [[0] * n for _ in range(n)]
    generate_helper(initial_matrix, 0, 0)

    return adjacency_matrices

# Example usage:
n = 3
result = generate_adjacency_matrices(n)
for matrix in result:
    mprint(matrix)


[0, 0, 0]
[0, 0, 0]
[0, 0, 0]

[0, 0, 0]
[0, 0, 1]
[0, 1, 0]

[0, 0, 1]
[0, 0, 0]
[1, 0, 0]

[0, 0, 1]
[0, 0, 1]
[1, 1, 0]

[0, 1, 0]
[1, 0, 0]
[0, 0, 0]

[0, 1, 0]
[1, 0, 1]
[0, 1, 0]

[0, 1, 1]
[1, 0, 0]
[1, 0, 0]

[0, 1, 1]
[1, 0, 1]
[1, 1, 0]



In [4]:
import numpy as np

def adjacency_to_laplacian(adjacency_matrix):
    """
    Convert an adjacency matrix to a Laplacian matrix.

    Args:
        adjacency_matrix: The adjacency matrix of the graph.

    Returns:
        The Laplacian matrix.
    """
    # Convert the adjacency matrix to a numpy array
    adjacency_matrix = np.array(adjacency_matrix)

    # Step 1: Compute the degree matrix
    degree_matrix = np.diag(np.sum(adjacency_matrix, axis=1))

    # Step 2: Compute the Laplacian matrix
    laplacian_matrix = degree_matrix - adjacency_matrix

    return laplacian_matrix

# Example usage:
adjacency_matrix = [
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0]
]

laplacian_matrix = adjacency_to_laplacian(adjacency_matrix)
print("Adjacency Matrix:")
print(np.array(adjacency_matrix))
print("\nLaplacian Matrix:")
print(laplacian_matrix)


Adjacency Matrix:
[[0 1 1]
 [1 0 1]
 [1 1 0]]

Laplacian Matrix:
[[ 2 -1 -1]
 [-1  2 -1]
 [-1 -1  2]]


In [5]:
import numpy as np

def spectral_decomposition(matrix, decimal_places=10):
    """
    Compute the spectral decomposition of a matrix.

    Args:
        matrix: The input matrix.
        decimal_places: Number of decimal places to round the eigenvalues and eigenvectors.

    Returns:
        rounded_eigenvalues: The rounded eigenvalues of the matrix.
        rounded_eigenvectors: The rounded corresponding eigenvectors.
    """
    # Compute eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(matrix)

    # Sort eigenvalues and corresponding eigenvectors
    sorted_indices = np.argsort(eigenvalues)
    eigenvalues = eigenvalues[sorted_indices]
    eigenvectors = eigenvectors[:, sorted_indices]

    # Round eigenvalues and eigenvectors to mitigate small computational errors
    rounded_eigenvalues = np.round(eigenvalues, decimal_places)
    rounded_eigenvectors = np.round(eigenvectors, decimal_places)

    return rounded_eigenvalues, rounded_eigenvectors

# Example usage:
any_matrix = np.array([
    [2, 1, 0],
    [1, 2, 1],
    [0, 1, 2]
])

eigenvalues, eigenvectors = spectral_decomposition(any_matrix)

# Print ordered and rounded eigenvalues and corresponding eigenvectors
for i, (value, vector) in enumerate(zip(eigenvalues, eigenvectors.T), 1):
    print(f"Eigenvalue {i}: {value}")
    print(f"Eigenvector {i}: {vector}")
    print()


Eigenvalue 1: 0.5857864376
Eigenvector 1: [ 0.5        -0.70710678  0.5       ]

Eigenvalue 2: 2.0
Eigenvector 2: [ 0.70710678  0.         -0.70710678]

Eigenvalue 3: 3.4142135624
Eigenvector 3: [-0.5        -0.70710678 -0.5       ]



In [6]:
import numpy as np

def combine_eigenvectors_by_norm(eigenvalues, eigenvectors):
    """
    Combine eigenvectors that correspond to the same eigenvalue by 2-norm.

    Args:
        eigenvalues: The eigenvalues of the matrix.
        eigenvectors: The corresponding eigenvectors.

    Returns:
        combined_eigenvalues: The unique eigenvalues.
        combined_eigenvectors: The combined eigenvectors.
    """
    combined_eigenvalues = []
    combined_eigenvectors = []

    unique_eigenvalues = np.unique(eigenvalues)

    for value in unique_eigenvalues:
        indices = np.where(eigenvalues == value)[0]
        combined_vector = np.linalg.norm(eigenvectors[:, indices], axis=1)

        combined_eigenvalues.append(value)
        combined_eigenvectors.append(combined_vector)

    combined_eigenvalues = np.array(combined_eigenvalues)
    combined_eigenvectors = np.column_stack(combined_eigenvectors)

    return combined_eigenvalues, combined_eigenvectors

# Example usage:
eigenvalues = np.array([1, 2, 2, 3, 3, 4])
eigenvectors = np.array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
              [0.2, 0.3, 0.4, 0.5, 0.6, 0.7],
              [0.3, 0.4, 0.5, 0.6, 0.7, 0.8]])

combined_eigenvalues, combined_eigenvectors = combine_eigenvectors_by_norm(eigenvalues, eigenvectors)

# Print combined eigenvalues and eigenvectors
for value, vector in zip(combined_eigenvalues, combined_eigenvectors.T):
    print(f"Eigenvalue {value}: Combined Eigenvector: {vector}")
    print()


Eigenvalue 1: Combined Eigenvector: [0.1 0.2 0.3]

Eigenvalue 2: Combined Eigenvector: [0.36055513 0.5        0.64031242]

Eigenvalue 3: Combined Eigenvector: [0.64031242 0.78102497 0.92195445]

Eigenvalue 4: Combined Eigenvector: [0.6 0.7 0.8]



In [7]:
import numpy as np

def sort_matrix_rows(matrix):
    """
    Sort the rows of a matrix in lexicographical (dictionary) order.

    Args:
        matrix: The input matrix.

    Returns:
        sorted_matrix: The matrix with sorted rows.
    """
    indices = np.lexsort(-matrix[:, ::-1].T)
    sorted_matrix = matrix[indices]

    return sorted_matrix, indices

# Example usage:
input_matrix = np.array([
    [3, 0, 1, 2],
    [3, 0, 4, 4],
    [0, 2, 2, 6]
])

sorted_matrix = sort_matrix_rows(input_matrix)

# Print the sorted matrix
print("Original Matrix:")
print(input_matrix)
print("\nSorted Matrix:")
print(sorted_matrix)


Original Matrix:
[[3 0 1 2]
 [3 0 4 4]
 [0 2 2 6]]

Sorted Matrix:
(array([[3, 0, 4, 4],
       [3, 0, 1, 2],
       [0, 2, 2, 6]]), array([1, 0, 2]))


# run

In [8]:
import numpy as np

def run(matrix):
    # Assuming you have the necessary functions defined
    L = adjacency_to_laplacian(matrix)
    eval, evec = spectral_decomposition(L)
    cval, cvec = combine_eigenvectors_by_norm(eval, evec)
    svec, indices = sort_matrix_rows(cvec)

    return eval, cval, svec, indices

# Example usage:
matrix_example = np.array([
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0]
])

eval, cval, svec, indices = run(matrix_example)

print("Combined Eigenvalues:")
print(cval)

print("\nSorted Eigenvectors:")
mprint(svec)


Combined Eigenvalues:
[-0.  3.]

Sorted Eigenvectors:
[0.57735027 0.90626217]
[0.57735027 0.87322126]
[0.57735027 0.64511512]



# binary_insert

In [9]:
def binary_search(arr, value, compare_func):
    low, high = 0, len(arr)

    while low < high:
        mid = (low + high) // 2  # Find the middle index

        comparison_result = compare_func(arr[mid], value)

        if comparison_result == 0:
            return mid, True
        elif comparison_result < 0:
            low = mid + 1  # Search in the right half
        else:
            high = mid  # Search in the left half or equal elements

    return low, False

# Example usage:
def custom_compare(a, b):
    # Your custom comparison function returning:
    # -1 if a < b, 0 if a == b, 1 if a > b
    if a < b:
        return -1
    elif a == b:
        return 0
    else:
        return 1

sorted_list = [1, 2, 4, 7, 10, 12, 15]
value_to_insert = 7

ind, bool = binary_search(sorted_list, value_to_insert, custom_compare)

print(f"List after binary insertion: {ind, bool}")


List after binary insertion: (3, True)


# class

In [49]:
class Cospectrum:
    def __init__(self, eval):
        self.eval = eval
        self.list = []
        self.count = 0
        self.dist = 0
    def add(self, G):
        if self.count == 0:
            col = Collection(G.eval, G.svec)
            self.dist += col.add(G)
            
            self.list.append(col)
            self.count += 1
            return 1
        
        idx, flag = binary_search(self.list, G, svec_compare)
        if flag == False:
            col = Collection(G.eval, G.svec)
            self.dist += col.add(G)
            
            self.list.insert(idx, col)
            self.count += 1
            return 1
        else:
            col = self.list[idx]
            self.dist += col.add(G)
            return 0

In [50]:
class Collection:
    def __init__(self, eval, svec):
        self.eval = eval
        self.svec = svec
        self.list = []
        self.count = 0
    def add(self, G):
        self.list.append(G)
        self.count += 1
        if self.count == 1:
            return 1
        elif self.count == 2:
            return -1
        else:
            return 0

In [51]:
class Gra:
    def __init__(self, matrix):
        self.A = matrix

        eval, cval, svec, indices = run(matrix)

        self.eval = eval
        self.cval = cval
        self.svec = svec
        self.indices = indices

# compare

In [52]:
def array_compare(a, b):

    l = len(a)
    for i in range(l):
        if a[i] < b[i]:
            return -1
        if a[i] > b[i]:
            return 1
    return 0

a = np.array([1, 2, 1])
b = np.array([1, 2, 3])

# 打印结果
print("Result of comparison:", array_compare(a, b))

Result of comparison: -1


In [53]:
def eval_compare(a, b):
    ea = a.eval
    eb = b.eval
    return array_compare(ea, eb)

# 创建两个数组
array1 = np.array([1, 2, 1])
array2 = np.array([1, 2, 3])
a = Cospectrum(array1)
b = Cospectrum(array2)

# 打印结果
print("Array 1:", array1)
print("Array 2:", array2)
print("Result of comparison:", eval_compare(a, b))

Array 1: [1 2 1]
Array 2: [1 2 3]
Result of comparison: -1


In [54]:
def svec_compare(a, b):
    va = a.svec
    vb = b.svec
    num_rows = va.shape[0]
    for i in range(num_rows):
        r = array_compare(va[i], vb[i])
        if r != 0:
            break
    return r

# 创建两个数组
array1 = np.array([[5, 2, 3], [1, 2, 2]])
array2 = np.array([[5, 2, 3], [1, 2, 3]])
a = Collection([0], array1)
b = Collection([0], array2)

# 打印结果
print("Array 1:", array1)
print("Array 2:", array2)
print("Result of comparison:", svec_compare(a, b))

Array 1: [[5 2 3]
 [1 2 2]]
Array 2: [[5 2 3]
 [1 2 3]]
Result of comparison: -1


# T3

In [55]:
def split(n, matrix_list):
    root = []
    ctr1, ctr2 = 0, 0
    for matrix in matrix_list:
        G = Gra(matrix)

        idx, flag = binary_search(root, G, eval_compare)

        if flag == False:
            cos = Cospectrum(G.eval)
            ctr2 += cos.add(G)
            
            root.insert(idx, cos)
            ctr1 += 1
            
        else:
            cos = root[idx]
            ctr2 += cos.add(G)
    return ctr1, ctr2

In [57]:
from sage.graphs.graph import Graph
from sage.graphs.graph_generators import graphs

for n in range(1, ㄅˇ):
    all_graphs = graphs.nauty_geng(str(n) + " -c")
    gist = []
    for g in all_graphs:
        gist.append(g.adjacency_matrix())
        
    #gist = generate_adjacency_matrices(n)
    
    ctr1, ctr2 = split(n, gist)
    print(f"n = {n}, len(root) = {ctr1}, totle = {ctr2}")

n = 1, len(root) = 1, totle = 1
n = 2, len(root) = 1, totle = 1
n = 3, len(root) = 2, totle = 2
n = 4, len(root) = 6, totle = 6
n = 5, len(root) = 21, totle = 21
n = 6, len(root) = 110, totle = 112
n = 7, len(root) = 793, totle = 853
n = 8, len(root) = 10251, totle = 11071
